replicas: 1

image: daocloud.io/daocloud/dce-kube-scheduler:v1.18.19.1

resources:
  limits:
    cpu: 300m
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 100Mi

schedulerKubeApiServerConfigFilePath: /etc/kubernetes/admin.conf
