{{- if not (lookup "rbac.authorization.k8s.io/v1" "ClusterRoleBinding" "" "cherry-io-admin-binding") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cherry-io-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cherry-io-role
subjects:
- kind: ServiceAccount
  name: cherry-io-admin
  namespace: {{ .Release.Namespace}}
{{- end }}
